[package]
name = "nbtdoc"
version = "0.1.0"
authors = ["MrYurihi <mryurihi2003@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license = "MIT OR Apache-2.0"

[dependencies]
nom = "5.0.1"